### PR TITLE
User panel fixes

### LINKED ISSUE #336: Alias Non Object Exception on Panel
**Describe the bug**
Encountered accessing https://projectcitybuild.com/panel/accounts/19622

**Additional context**
```
[previous exception] [object] (ErrorException(code: 0): Trying to get property 'alias' of non-object at /var/www/projectcitybuild.com/app/Entities/Players/Models/MinecraftPlayer.php:42)
[stacktrace]
#0 /var/www/projectcitybuild.com/app/Entities/Players/Models/MinecraftPlayer.php(42): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/projectcitybuild.com/app/Entities/Bans/Models/GameBan.php(68): App\\Entities\\Players\\Models\\MinecraftPlayer->getBanReadableName()
#2 /var/www/projectcitybuild.com/storage/framework/views/08be7169ad3c7f787f8a22a3b58417c143e3e63c.php(287): App\\Entities\\Bans\\Models\\GameBan->getStaffName()
#3 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('/var/www/projec...')
#4 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#5 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#6 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#7 /var/www/projectcitybuild.com/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/ViewEngineDecorator.php(46): Illuminate\\View\\Engines\\CompilerEngine->get()
#8 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/View/View.php(139): Sentry\\Laravel\\Tracing\\ViewEngineDecorator->get()
#9 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#10 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#11 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(62): Illuminate\\View\\View->render()
#12 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\\Http\\Response->setContent()
#13 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(780): Illuminate\\Http\\Response->__construct()
#14 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(752): Illuminate\\Routing\\Router::toResponse()
#15 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Router->prepareResponse()
#16 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#17 /var/www/projectcitybuild.com/app/Http/Middleware/MfaGate.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\MfaGate->handle()
#19 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#21 /var/www/projectcitybuild.com/app/Http/Middleware/PanelAccess.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\PanelAccess->handle()
#23 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#27 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#29 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#30 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#32 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then()
#36 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute()
#38 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute()
#39 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#40 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 /var/www/projectcitybuild.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#43 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#49 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#51 /var/www/projectcitybuild.com/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Sentry\\Laravel\\Tracing\\Middleware->handle()
#53 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#55 /var/www/projectcitybuild.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /var/www/projectcitybuild.com/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
```

### PR DESCRIPTION
**Pull request by freddyheppell**
## Overview of Changes
- [x] Fix stray dollar signs on donation id
- [x] Add edit links to donations/perks
- [x] Fix non-object on ban staff name (fixes #336)

## Deployment Requirements
- [ ] Composer update
- [ ] NPM update
- [ ] Database migration
- [ ] .env update
- [ ] Environment upgrade (eg. PHP version)
- [ ] Other (please specify)

### CODE REVIEW

File: tests/Feature/PanelAccountTest.php [hunk 1]
```diff
@@ -60,4 +62,22 @@ public function testAccountDetailsChange()
 
         $this->assertDatabaseHas('accounts', $newData);
     }
+
+    public function testBanWithNoAliases()
+    {
+        $banningStaffAccount = Account::factory()->has(MinecraftPlayer::factory()->count(1), 'minecraftAccount')->create();
```
Comment (andyksaw) [inline tests/Feature/PanelAccountTest.php:68]: If it's just 1 model, I think `count(1)` is unneeded

**Review by andyksaw — APPROVED** [review]
