### PR TITLE
Fix null staff player panel bug

### LINKED ISSUE #413: ErrorException: Missing required parameter for [Route: front.panel.minecraft-players.show] [URI: panel/minecraft-...
Sentry Issue: [PCB-WEB-96](https://sentry.io/organizations/projectcitybuild/issues/2506763695/?referrer=github_integration)

Some bans have a null staff user

### LINKED ISSUE #428: Error: Call to a member function getUuid() on null
Sentry Issue: [PCB-WEB-97](https://sentry.io/organizations/projectcitybuild/issues/2513156613/?referrer=github_integration)

```
Error: Call to a member function getUuid() on null
  File "/app/Http/Controllers/Panel/MinecraftPlayerLookupController.php", line 67, in App\Http\Controllers\Panel\MinecraftPlayerLookupController::lookupByLiveAlias
    return $this->lookupByUUID($mojangPlayer->getUuid());
  File "/app/Http/Controllers/Panel/MinecraftPlayerLookupController.php", line 84, in App\Http\Controllers\Panel\MinecraftPlayerLookupController::__invoke
    $this->lookupByLiveAlias($query);
  File "/app/Http/Middleware/MfaGate.php", line 40, in App\Http\Middleware\MfaGate::handle
    return $next($request);
  File "/app/Http/Middleware/PanelAccess.php", line 21, in App\Http\Middleware\PanelAccess::handle
    return $next($request);
  File "/public/index.php", line 57
    $request = Illuminate\Http\Request::capture()
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by freddyheppell**
## Overview of Changes
* Fixes bug when player was banned by null player (maybe this happens when the console does it?) (fixes #413)
* Fixes bug when an unregistered username is entered into lookup (fixes #428)
   * This should've been tested but due to a non-mocked Mojang API instance we were making real queries. To stop this happening again the class is now globally mocked, so it'll error if not locally mocked
* Explicitly test what happens if you lookup "" or `null`

Coverage does decrease in this PR but that's because we're now never invoking the real Mojang API class.

## Deployment Requirements
- [ ] Composer update
- [ ] NPM update
- [ ] Database migration
- [ ] .env update
- [ ] Environment upgrade (eg. PHP version)
- [ ] Other (please specify)

### CODE REVIEW

File: database/factories/GameBanFactory.php [hunk 1]
```diff
@@ -99,4 +99,13 @@ public function bannedBy(MinecraftPlayer $minecraftPlayer): GameBanFactory
             ];
         });
     }
+
+    public function nullBannedBy(): GameBanFactory
```
Comment (andyksaw) [inline database/factories/GameBanFactory.php:103]: Null banner = console

Maybe better to call this `bannedByConsole`?

File: database/factories/GameBanFactory.php [hunk 2]
```diff
@@ -99,4 +99,13 @@ public function bannedBy(MinecraftPlayer $minecraftPlayer): GameBanFactory
...
+    {
+        return $this->state(function (array $attributes) {
+            return [
+                'staff_player_type' => 'minecraft_player',
```
Comment (andyksaw) [inline database/factories/GameBanFactory.php:107]: Is it okay not to explicitly set the staff player id to `null`?

**Review by andyksaw — APPROVED** [review]
Just a few nitpicks. Thanks for the fixes 👍
