### PR TITLE
Fix account search error if user has not logged in

### LINKED ISSUE #654: Account search fails if last logged in is null
Sentry Issue: [PCB-WEB-DY](https://sentry.io/organizations/projectcitybuild/issues/3540377395/?referrer=github_integration)

```
Error: Call to a member function getTimestamp() on null
  File "/entities/Resources/AccountResource.php", line 20, in Entities\Resources\AccountResource::toArray
    'last_login_at' => $this->last_login_at->getTimestamp(),
  File "/app/Http/Middleware/RequiresMfaEnabled.php", line 16, in App\Http\Middleware\RequiresMfaEnabled::handle
    return $next($request);
  File "/app/Http/Middleware/HasGroupScope.php", line 32, in App\Http\Middleware\HasGroupScope::handle
    return $next($request);
  File "/app/Http/Middleware/MfaGate.php", line 42, in App\Http\Middleware\MfaGate::handle
    return $next($request);
  File "/public/index.php", line 57
    $request = Illuminate\Http\Request::capture()
...
(58 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by freddyheppell**
## Overview of Changes
* Make usage of `getTimestamp()` on `last_login_at` null-safe (fixes #654)
* Add test
* Make factories use base class, with a method to add `created_at` and `updated_at` timestamps (useful if you `make()` a factory, but still need timestamps)

## Deployment Requirements
- [ ] Composer update
- [ ] NPM update
- [ ] Database migration
- [ ] .env update
- [ ] Environment upgrade (eg. PHP version)
- [ ] Other (please specify)

### CODE REVIEW

File: database/factories/Factory.php [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+     */
+    public function withTimestamps()
+    {
+        return $this->state(function (array $attributes) {
+            return [
+                'created_at' => now(),
+                'updated_at' => now(),
+            ];
+        });
+    }
```
Comment (andyksaw) [inline database/factories/Factory.php:19]: Oo this will be useful 🤩

**Review by andyksaw — APPROVED** [review]
LGTM!
