### PR TITLE
Fix donator role management

### LINKED ISSUE #265: Members don't get member rank back when donator perks expire
When donator perks auto-expire they don't get the Member rank back. Ideally I think we should force users to be in at least the members group when any rank changes are made

### LINKED ISSUE #272: Donator rank is added in addition to the Member rank
**Describe the bug**
When members donate, they are assigned both the member and donator rank, rather than the donator rank replacing the member rank.

**Expected behavior**
Usually it would be expected that a members primary rank would be replaced by the donator rank, whilst other higher ranks, would have the donator rank applied as a secondary rank.

### PR DESCRIPTION
**Pull request by freddyheppell**
## Overview of Changes
* Re-add the default group if expiring donations gives users no groups (fixes #265)
* Remove the Member group when someone donates (fixes #272)
* Notify users via email when their donation perks end
* Added a page to the user settings where users can see donation history
* PCB-ify email theme (see below)

## Deployment Requirements
- [x] Composer update
- [ ] NPM update
- [ ] Database migration
- [x] .env update
  - Make sure `MAIL_FROM_ADDRESS` and `MAIL_FROM_NAME` are set properly
- [ ] Environment upgrade (eg. PHP version)
- [ ] Other (please specify)
  - [x] Clear view cache

## Screenshots
It's quite hard to test trigger the donation expiry email so here it is. All emails now use this theme.
Screenshot 2020-12-21 at 14 51 47

### CODE REVIEW

**Comment by freddyheppell** [comment]
We _realllly realllly realllllllly_ need automated tests for the webhook endpoint but it's very complex and I'm not really familiar enough with that code. I've put in the fix so the member group is removed upon donation and manually tested.

File: app/Console/Commands/DeactivateDonatorPerksCommand.php [hunk 1]
```diff
@@ -80,9 +86,17 @@ public function handle()
                         $this->syncAction->syncAll();
 
                         $expiredPerk->account->groups()->detach($donatorGroup->getKey());
+
+                        $expiredPerk->account->load("groups");
```
Comment (andyksaw) [inline app/Console/Commands/DeactivateDonatorPerksCommand.php:90]: Just a tiny nit for consistency
```suggestion
                        $expiredPerk->account->load('groups');
```

Comment (andyksaw) [reply app/Console/Commands/DeactivateDonatorPerksCommand.php:90]: Though I feel like we're doing something to wrong to need to call `load` after every group modification 🤔

File: app/Entities/Donations/Models/DonationPerk.php [hunk 2]
```diff
@@ -70,8 +71,13 @@ public function account(): HasOne
...
-    public function donation(): HasOne
+    public function donation(): BelongsTo
     {
-        return $this->hasOne(Donation::class, 'donation_id', 'donation_id');
+        return $this->belongsTo(Donation::class, 'donation_id', 'donation_id');
+    }
+
+    public function humanReadableStatus()
+    {
+        return $this->is_active ? "Active" : "Expired";
```
Comment (andyksaw) [inline app/Entities/Donations/Models/DonationPerk.php:81]:
```suggestion
        return $this->is_active ? 'Active' : 'Expired';
```

File: app/Entities/Donations/Notifications/DonationEndedNotification.php [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+     * @return \Illuminate\Notifications\Messages\MailMessage
+     */
+    public function toMail($notifiable)
+    {
+        return (new MailMessage)
+                    ->subject('Your Donation has Ended')
+                    ->line('Your period of Donator has now ended and you\'ve been reset to your previous rank.')
+                    ->line('Thank you for helping support PCB - contributions from our members are the only way we can keep running! If you would like to keep supporting us, you can extend your donation here')
+                    ->action('Extend your donation', action('DonationController@index'))
+                    ->line('If you have any questions, please ask a member of PCB staff on our forums or discord');
```
Comment (andyksaw) [inline app/Entities/Donations/Notifications/DonationEndedNotification.php:48]: 😍

File: database/factories/Donations/DonationPerkFactory.php [hunk 4]
```diff
@@ -13,9 +13,15 @@
...
+        'is_lifetime_perks' => false,
         'expires_at' => $faker->dateTime(),
         'created_at' => $faker->dateTime(),
         'updated_at' => $faker->dateTime(),
     ];
-});
\ No newline at end of file
+});
+
+$factory->state(DonationPerk::class,'lifetime', function() {
```
Comment (andyksaw) [inline database/factories/Donations/DonationPerkFactory.php:23]:
```suggestion
$factory->state(DonationPerk::class, 'lifetime', function() {
```

File: database/seeders/AccountSeeder.php [hunk 5]
```diff
@@ -14,6 +15,8 @@ class AccountSeeder extends Seeder
      */
     public function run()
     {
-        factory(Account::class, 500)->create();
+        $account = factory(Account::class, 500)->create();
+        $defaultGroup = Group::where('is_default',1)->first();
```
Comment (andyksaw) [inline database/seeders/AccountSeeder.php:19]:
```suggestion
        $defaultGroup = Group::where('is_default', 1)->first();
```

File: resources/views/front/pages/account/account-donations.blade.php [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+                            <th>Expires</th>
+                            <th>Status</th>
+                        </tr>
+                        </thead>
+                        <tbody>
+                        @foreach($donationPerks as $perk)
+                            <tr>
+                                @if($perk->donation != null)
+                                    <td>{{ $perk->donation->created_at->toFormattedDateString() }}</td>
+                                    <td>${{ number_format($perk->donation->amount,2) }}</td>
```
Comment (andyksaw) [inline resources/views/front/pages/account/account-donations.blade.php:35]:
```suggestion
                                    <td>${{ number_format($perk->donation->amount, 2) }}</td>
```

File: resources/sass/global/_typography.scss [hunk 7]
```diff
@@ -19,6 +19,14 @@ h1, h2, h3, h4, h5, h6 {
...
 }
 
+.mb-0 {
+    margin-bottom: 0;
+}
+
+.mt-0 {
+    margin-top: 0;
+}
+
```
Comment (freddyheppell) [inline resources/sass/global/_typography.scss:29]: Oops, meant to remove these as I ended up making a stylesheet for this page

File: app/Entities/Donations/Models/DonationPerk.php [hunk 8]
```diff
@@ -70,8 +71,13 @@ public function account(): HasOne
...
     }
 
-    public function donation(): HasOne
+    public function donation(): BelongsTo
     {
-        return $this->hasOne(Donation::class, 'donation_id', 'donation_id');
+        return $this->belongsTo(Donation::class, 'donation_id', 'donation_id');
+    }
+
+    public function humanReadableStatus()
```
Comment (andyksaw) [inline app/Entities/Donations/Models/DonationPerk.php:79]: I'm a bit conflicted about these kind of functions. On one hand, it's "view" logic and shouldn't be in a model, but on the other hand, Laravel models are very far from plain-old-data-objects either 🤔

File: app/Console/Commands/DeactivateDonatorPerksCommand.php (hunk 1 above)
Comment (freddyheppell) [reply app/Console/Commands/DeactivateDonatorPerksCommand.php:90]: It's a weird one but I run into this all the time. I believe it's just a side effect of the way attach and detach works with respect to the memory representation of models, where it doesn't re-query the DB to see what relationships were actually created for performance reason.

File: app/Entities/Donations/Models/DonationPerk.php (hunk 8 above)
Comment (freddyheppell) [reply app/Entities/Donations/Models/DonationPerk.php:79]: Ah yep, originally the logic was a bit more complex as the status took into account whether it was lifetime or not, but I ended up displaying that in the expiry column instead making this a bit more useless.

File: resources/views/front/pages/account/account-donations.blade.php [hunk 9]
```diff
@@ -0,0 +1,61 @@
...
+                            <th>Date</th>
+                            <th>Amount</th>
+                            <th>Expires</th>
+                            <th>Status</th>
+                        </tr>
+                        </thead>
+                        <tbody>
+                        @foreach($donationPerks as $perk)
+                            <tr>
+                                @if($perk->donation != null)
```
Comment (andyksaw) [inline resources/views/front/pages/account/account-donations.blade.php:33]: Is the aim of this screen to show how much you've donated? Or to check when your perks end?

If it's the former, maybe the simplest approach is to show the perk in the same row as the donation like
|Date|Amount|Perk Receiver|Perk Expires|Status|
|--|--|--|--|--|
|...|$3.00|_andy|...|Active|

Comment (freddyheppell) [reply resources/views/front/pages/account/account-donations.blade.php:33]: I did consider whether to properly represent the fact donator/perks are separate, but decided that since seeing when your perks expire is probably most important I'd do it this way.

I could add a table that shows if you've got perks for other people but decided not to initially since it's a much more complex query, it's not something we currently actually give people a way to do officially and I'm not sure how many times it's actually been done

Comment (andyksaw) [reply resources/views/front/pages/account/account-donations.blade.php:33]: Ah that's true, I forgot we've been doing that manually. Let's roll with this 👍

Comment (freddyheppell) [reply resources/views/front/pages/account/account-donations.blade.php:33]: The null check here is because I wasn't sure if it was possible to create perks not linked with a donation. Turns out it's not (currently) so maybe that isn't required, but also I'm inclined to just leave it in, in case we modify things to do support that in the future.

**Review by andyksaw — APPROVED** [review]
Just a few nit picks, but overall looks solid. Thanks a lot!

File: resources/views/front/pages/account/account-donations.blade.php (hunk 9 above)
Comment (andyksaw) [reply resources/views/front/pages/account/account-donations.blade.php:33]: If we do get around to letting people choose the perk recipient, we'll likely have to allow multiple people to be recipients - but I imagine that's going to be a bit nightmarish to code 😢
